// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxpnTphLa-G78g8WpvOj5xUSc-LR-3Dos',
    appId: '1:853715405431:web:56c139507fabaddfdfd472',
    messagingSenderId: '853715405431',
    projectId: 'flutterfirebase-b3f18',
    authDomain: 'flutterfirebase-b3f18.firebaseapp.com',
    storageBucket: 'flutterfirebase-b3f18.appspot.com',
    measurementId: 'G-66E829PR4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjT-7-FqtIMHGvnW0iD_LU9FEQ84hlNgE',
    appId: '1:853715405431:android:3a675d8dbb104e7fdfd472',
    messagingSenderId: '853715405431',
    projectId: 'flutterfirebase-b3f18',
    storageBucket: 'flutterfirebase-b3f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA5nLnmHzghgM4gJCtG87hdmZKDjaaeQc',
    appId: '1:853715405431:ios:087fbc4cdd5cae54dfd472',
    messagingSenderId: '853715405431',
    projectId: 'flutterfirebase-b3f18',
    storageBucket: 'flutterfirebase-b3f18.appspot.com',
    androidClientId: '853715405431-a06qmpt0o4f07m6nvflk3vtif970ma2g.apps.googleusercontent.com',
    iosClientId: '853715405431-eccgq016m0tc3etjgemq2dorcua40uhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.testflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA5nLnmHzghgM4gJCtG87hdmZKDjaaeQc',
    appId: '1:853715405431:ios:5192f5023c1e4bcedfd472',
    messagingSenderId: '853715405431',
    projectId: 'flutterfirebase-b3f18',
    storageBucket: 'flutterfirebase-b3f18.appspot.com',
    androidClientId: '853715405431-a06qmpt0o4f07m6nvflk3vtif970ma2g.apps.googleusercontent.com',
    iosClientId: '853715405431-oujj6fqsk77gkpu5gtjgv1len3k13gb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.testflutter.RunnerTests',
  );
}
